name: DUALERT
description: "An Emergency Alert Security System for Dominion University"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  firebase_core: ^3.7.0
  cloud_firestore: ^5.3.0
  firebase_auth: ^5.1.3
  uuid: ^4.5.2
  flutter_svg: ^2.1.0
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
fonts:
    - family: Montserrat
      fonts:
        - asset: asset/fonts/Montserrat-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: asset/fonts/Montserrat-Thin.ttf
          style: normal
          weight: 100
        - asset: asset/fonts/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 800
        - asset: asset/fonts/Montserrat-SemiBold.ttf
          style: normal
          weight: 800
        - asset: asset/fonts/Montserrat-Regular.ttf
          style: normal
          weight: 400
        - asset: asset/fonts/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: asset/fonts/Montserrat-Medium.ttf
          style: normal
          weight: 500
        - asset: asset/fonts/Montserrat-Italic.ttf
          style: normal
          weight: 400
        - asset: asset/fonts/Montserrat-ExtraBold.ttf
          style: normal
          weight: 900
        - asset: asset/fonts/Montserrat-BoldItalic.ttf
          style: italic
          weight: 900
        - asset: asset\fonts\Montserrat-Black.ttf
          style: italic
        - asset: asset\fonts\Montserrat-Black.ttf
          style: normal
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
